<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CampusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $accreditation = DB::table('accreditations')->where('name', 'Baik Sekali')->first();
        $ptn_id = DB::table('campus_types')->where('name', 'PTN')->value('id');
        $politeknik_id = DB::table('campus_types')->where('name', 'Politeknik')->value('id');
        $swasta_id = DB::table('campus_types')->where('name', 'Swasta')->value('id');

        $unggul_id = DB::table('accreditations')->where('name', 'Unggul')->value('id');
        $baik_sekali_id = DB::table('accreditations')->where('name', 'Baik Sekali')->value('id');
        $a_id = DB::table('accreditations')->where('name', 'A')->value('id');

        if ($accreditation) {
            DB::table('campuses')->insert([
                [
                    'name' => 'Politeknik Negeri Semarang',
                    'description' => 'Kec. Tembalang, Kota Semarang',
                    'date_of_establishment' => '1997-08-06',
                    'logo_path' => '/logo/logo_polines.png',
                    'address_latitude' => (float) -7.051078422420263,
                    'address_longitude' => (float) 110.4355492767185,
                    'web_address' => 'https://www.polines.ac.id',
                    'phone_number' => '0247473417',
                    'email' => 'sekretariat@polines.ac.id',
                    'youtube' => 'https://www.youtube.com/channel/UCpjWNObWb1De5StIxQ_7pZA',
                    'instagram' => 'https://www.instagram.com/polinesofficial',
                    'number_of_graduates' => 1500,
                    'number_of_registrants' => 3000,
                    'min_single_tuition'=> 500000,
                    'max_single_tuition'=> 7500000,
                    'campus_type_id' => $politeknik_id,
                    'accreditation_id' => $a_id,
                    'district_id' => 3181,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],


                [
                    'name' => 'Universitas Negeri Semarang',
                    'description' => 'Kec. Gunungpati, Kota Semarang',
                    'date_of_establishment' => '1999-09-09',
                    'logo_path' => '/logo/logo_unnes.png',
                    'address_latitude' => (float) -7.050459040075577,
                    'address_longitude' => (float) 110.3924514329852,
                    'web_address' => 'https://unnes.ac.id',
                    'phone_number' => '024-86008700',
                    'email' => 'humas@mail.unnes.ac.id',
                    'youtube' => 'https://www.youtube.com/@UNNESTV',
                    'instagram' => 'https://www.instagram.com/unnes_semarang/',
                    'number_of_graduates' => 700,
                    'number_of_registrants' => 1100,
                    'min_single_tuition'=> 500000,
                    'max_single_tuition'=> 22000000,
                    'accreditation_id' => $unggul_id,
                    'campus_type_id' => $ptn_id,
                    'district_id' => 3183,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Dian Nuswantoro',
                    'description' => 'Kec. Semarang Tengah, Kota Semarang',
                    'date_of_establishment' => '1990-11-13',
                    'logo_path' => '/logo/logo_udinus.png',
                    'address_latitude' => (float) -6.981614114225112,
                    'address_longitude' => (float) 110.40927468580766,
                    'web_address' => 'https://dinus.ac.id',
                    'phone_number' => '024-3517261',
                    'email' => 'sekretariat@dinus.id',
                    'youtube' => 'https://www.youtube.com/@tvku_udinus',
                    'instagram' => 'https://www.instagram.com/udinusofficial/#',
                    'number_of_graduates' => 650,
                    'number_of_registrants' => 1000,
                    'min_single_tuition'=> 4625000,
                    'max_single_tuition'=> 9250000,
                    'accreditation_id' => $unggul_id,
                    'campus_type_id' => $swasta_id,
                    'district_id' => 3172,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Indonesia',
                    'description' => 'Kecamatan Beji, Kota Depok',
                    'date_of_establishment' => '1849-02-02',
                    'logo_path' => '/logo/logo_ui.png',
                    'address_latitude' => (float) -6.362314,
                    'address_longitude' => (float) 106.827139,
                    'web_address' => 'https://ui.ac.id',
                    'phone_number' => '021-7867222',
                    'email' => 'info@ui.ac.id',
                    'youtube' => 'https://www.youtube.com/universitasindonesia',
                    'instagram' => 'https://www.instagram.com/univ_indonesia',
                    'number_of_graduates' => 10000,
                    'number_of_registrants' => 35000,
                    'min_single_tuition' => 500000,
                    'max_single_tuition' => 25000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => 2597, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                
                [
                    'name' => 'Universitas Gadjah Mada',
                    'description' => 'Kec. Sleman, Kabupaten Sleman, Yogyakarta',
                    'date_of_establishment' => '1949-12-19',
                    'logo_path' => '/logo/logo_ugm.png',
                    'address_latitude' => (float) -7.783493,
                    'address_longitude' => (float) 110.379073,
                    'web_address' => 'https://ugm.ac.id',
                    'phone_number' => '0274-588688',
                    'email' => 'info@ugm.ac.id',
                    'youtube' => 'https://www.youtube.com/user/UGMOfficialChannel',
                    'instagram' => 'https://www.instagram.com/ugm_official',
                    'number_of_graduates' => 13000,
                    'number_of_registrants' => 50000,
                    'min_single_tuition' => 700000,
                    'max_single_tuition' => 25000000,
                    'accreditation_id' => $unggul_id,
                    'campus_type_id' => $ptn_id, 
                    'district_id' => 3255, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Diponegoro',
                    'description' => 'Kec. Tembalang, Kota Semarang',
                    'date_of_establishment' => '1956-11-10',
                    'logo_path' => '/logo/logo_undip.png',
                    'address_latitude' => (float) -7.0515187389640355,
                    'address_longitude' => (float) 110.4408874135232,
                    'web_address' => 'https://undip.ac.id',
                    'phone_number' => '024-76918188',
                    'email' => 'info@undip.ac.id',
                    'youtube' => 'https://www.youtube.com/c/UNDIPOfficial',
                    'instagram' => 'https://www.instagram.com/undip_official',
                    'number_of_graduates' => 12000,
                    'number_of_registrants' => 30000,
                    'min_single_tuition' => 600000,
                    'max_single_tuition' => 25000000,
                    'accreditation_id' => $unggul_id,
                    'campus_type_id' => $ptn_id,
                    'district_id' => 3181, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Airlangga',
                    'description' => 'Kec. Mulyorejo, Kota Surabaya',
                    'date_of_establishment' => '1954-11-10',
                    'logo_path' => '/logo/logo_unair.png',
                    'address_latitude' => (float) -7.282963,
                    'address_longitude' => (float) 112.768712,
                    'web_address' => 'https://unair.ac.id',
                    'phone_number' => '031-5995151',
                    'email' => 'info@unair.ac.id',
                    'youtube' => 'https://www.youtube.com/c/UniversitasAirlanggaOfficial',
                    'instagram' => 'https://www.instagram.com/unair_official',
                    'number_of_graduates' => 15000,
                    'number_of_registrants' => 40000,
                    'min_single_tuition' => 700000,
                    'max_single_tuition' => 25000000,
                    'accreditation_id' => $unggul_id,
                    'campus_type_id' => $ptn_id,
                    'district_id' => 3931, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Institut Pertanian Bogor',
                    'description' => 'Kec. Dramaga, Kabupaten Bogor, Jawa Barat',
                    'date_of_establishment' => '1963-09-01',
                    'logo_path' => '/logo/logo_ipb.png',
                    'address_latitude' => (float) -6.595564,
                    'address_longitude' => (float) 106.793008,
                    'web_address' => 'https://ipb.ac.id',
                    'phone_number' => '0251-8625600',
                    'email' => 'info@ipb.ac.id',
                    'youtube' => 'https://www.youtube.com/c/InstitutPertanianBogor',
                    'instagram' => 'https://www.instagram.com/ipb_university',
                    'number_of_graduates' => 8000,
                    'number_of_registrants' => 25000,
                    'min_single_tuition' => 1000000,
                    'max_single_tuition' => 25000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => 2022, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Brawijaya',
                    'description' => 'Kec. Lowokwaru, Kota Malang',
                    'date_of_establishment' => '1963-01-05',
                    'logo_path' => '/logo/logo_ub.png',
                    'address_latitude' => (float) -7.982531,
                    'address_longitude' => (float) 112.634412,
                    'web_address' => 'https://ub.ac.id',
                    'phone_number' => '0341-575800',
                    'email' => 'info@ub.ac.id',
                    'youtube' => 'https://www.youtube.com/c/UniversitasBrawijayaOfficial',
                    'instagram' => 'https://www.instagram.com/ub_official',
                    'number_of_graduates' => 12000,
                    'number_of_registrants' => 35000,
                    'min_single_tuition' => 700000,
                    'max_single_tuition' => 25000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => 3890, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Institut Teknologi Bandung',
                    'description' => 'Kec. Coblong, Kota Bandung',
                    'date_of_establishment' => '1959-03-02',
                    'logo_path' => '/logo/logo_itb.png',
                    'address_latitude' => (float) -6.890473,
                    'address_longitude' => (float) 107.610939,
                    'web_address' => 'https://itb.ac.id',
                    'phone_number' => '022-2500930',
                    'email' => 'info@itb.ac.id',
                    'youtube' => 'https://www.youtube.com/c/ITBChannel',
                    'instagram' => 'https://www.instagram.com/itbofficial',
                    'number_of_graduates' => 9000,
                    'number_of_registrants' => 30000,
                    'min_single_tuition' => 800000,
                    'max_single_tuition' => 25000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => 2546, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Negeri Sebelas Maret',
                    'description' => 'Kec. Jebres, Kota Surakarta',
                    'date_of_establishment' => '1976-03-11',
                    'logo_path' => '/logo/logo_uns.png',
                    'address_latitude' => (float) -7.550799,
                    'address_longitude' => (float) 110.821563,
                    'web_address' => 'https://uns.ac.id',
                    'phone_number' => '0271-632335',
                    'email' => 'uns@uns.ac.id',
                    'youtube' => 'https://www.youtube.com/c/UniversitasNegeriSebelasMaret',
                    'instagram' => 'https://www.instagram.com/uns_solo',
                    'number_of_graduates' => 10000,
                    'number_of_registrants' => 25000,
                    'min_single_tuition' => 700000,
                    'max_single_tuition' => 25000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id,
                    'district_id' => 3166, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Sumatera Utara',
                    'description' => 'Kec. Medan Timur, Kota Medan',
                    'date_of_establishment' => '1952-11-04',
                    'logo_path' => '/logo/logo_usu.png',
                    'address_latitude' => (float) 3.595398,
                    'address_longitude' => (float) 98.674548,
                    'web_address' => 'https://usu.ac.id',
                    'phone_number' => '061-7360123',
                    'email' => 'info@usu.ac.id',
                    'youtube' => 'https://www.youtube.com/c/UniversitasSumateraUtara',
                    'instagram' => 'https://www.instagram.com/usu_official',
                    'number_of_graduates' => 11000,
                    'number_of_registrants' => 30000,
                    'min_single_tuition' => 800000,
                    'max_single_tuition' => 24000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => 698,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Pendidikan Ganesha',
                    'description' => 'Kec. Singaraja, Kabupaten Buleleng, Bali',
                    'date_of_establishment' => '2006-10-31',
                    'logo_path' => '/logo/logo_undiksha.png',
                    'address_latitude' => (float) -8.109366,
                    'address_longitude' => (float) 115.085073,
                    'web_address' => 'https://undiksha.ac.id',
                    'phone_number' => '0362-22403',
                    'email' => 'info@undiksha.ac.id',
                    'youtube' => 'https://www.youtube.com/c/UniversitasPendidikanGanesha',
                    'instagram' => 'https://www.instagram.com/undikshaofficial',
                    'number_of_graduates' => 5000,
                    'number_of_registrants' => 12000,
                    'min_single_tuition' => 600000,
                    'max_single_tuition' => 15000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => null, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Andalas',
                    'description' => 'Kec. Limau Manis, Kota Padang',
                    'date_of_establishment' => '1956-12-23',
                    'logo_path' => '/logo/logo_unand.png',
                    'address_latitude' => (float) -0.953410,
                    'address_longitude' => (float) 100.393265,
                    'web_address' => 'https://unand.ac.id',
                    'phone_number' => '0751-705309',
                    'email' => 'info@unand.ac.id',
                    'youtube' => 'https://www.youtube.com/c/UniversitasAndalas',
                    'instagram' => 'https://www.instagram.com/unandpadang',
                    'number_of_graduates' => 12000,
                    'number_of_registrants' => 25000,
                    'min_single_tuition' => 800000,
                    'max_single_tuition' => 20000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Pelita Harapan',
                    'description' => 'Kec. Karawaci, Kota Tangerang',
                    'date_of_establishment' => '1994-11-11',
                    'logo_path' => '/logo/logo_uph.png',
                    'address_latitude' => (float) -6.194051,
                    'address_longitude' => (float) 106.637282,
                    'web_address' => 'https://uph.edu',
                    'phone_number' => '021-5460901',
                    'email' => 'info@uph.edu',
                    'youtube' => 'https://www.youtube.com/c/UniversitasPelitaHarpan',
                    'instagram' => 'https://www.instagram.com/uph_university',
                    'number_of_graduates' => 7000,
                    'number_of_registrants' => 15000,
                    'min_single_tuition' => 8000000,
                    'max_single_tuition' => 25000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $swasta_id, 
                    'district_id' => 4067, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Sriwijaya',
                    'description' => 'Kec. Tanjung Raja, Kabupaten Ogan Ilir, Sumatera Selatan',
                    'date_of_establishment' => '1960-09-01',
                    'logo_path' => '/logo/logo_unsri.png',
                    'address_latitude' => (float) -3.3365561,
                    'address_longitude' => (float) 104.7404269,
                    'web_address' => 'https://unsri.ac.id',
                    'phone_number' => '0711-580213',
                    'email' => 'unsri@unsri.ac.id',
                    'youtube' => 'https://www.youtube.com/c/UniversitasSriwijaya',
                    'instagram' => 'https://www.instagram.com/unsri_official',
                    'number_of_graduates' => 15000,
                    'number_of_registrants' => 30000,
                    'min_single_tuition' => 1000000,
                    'max_single_tuition' => 25000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => 1397, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Udayana',
                    'description' => 'Kec. KUTA SELATAN, Kabupaten Badung, Bali',
                    'date_of_establishment' => '1962-02-29',
                    'logo_path' => '/logo/logo_unud.png',
                    'address_latitude' => (float) -8.7815919,
                    'address_longitude' => (float) 115.1787738,
                    'web_address' => 'https://unud.ac.id',
                    'phone_number' => '0361-701255',
                    'email' => 'info@unud.ac.id',
                    'youtube' => 'https://www.youtube.com/c/UniversitasUdayana',
                    'instagram' => 'https://www.instagram.com/unudbali',
                    'number_of_graduates' => 10000,
                    'number_of_registrants' => 25000,
                    'min_single_tuition' => 900000,
                    'max_single_tuition' => 20000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => 411, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Telkom University',
                    'description' => 'Kec. Dayeuhkolot, Kabupaten Bandung',
                    'date_of_establishment' => '2013-10-01',
                    'logo_path' => '/logo/logo_telkom_university.png',
                    'address_latitude' => (float) -6.971892,
                    'address_longitude' => (float) 107.612654,
                    'web_address' => 'https://telkomuniversity.ac.id',
                    'phone_number' => '022-7101010',
                    'email' => 'info@telkomuniversity.ac.id',
                    'youtube' => 'https://www.youtube.com/c/TelkomUniversityOfficial',
                    'instagram' => 'https://www.instagram.com/telkomuniversity',
                    'number_of_graduates' => 5000,
                    'number_of_registrants' => 15000,
                    'min_single_tuition' => 1000000,
                    'max_single_tuition' => 25000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $swasta_id, 
                    'district_id' => 2119, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Negeri Malang',
                    'description' => 'Kec. Lowokwaru, Kota Malang',
                    'date_of_establishment' => '1954-10-18',
                    'logo_path' => '/logo/logo_um.png',
                    'address_latitude' => (float) -7.9370268,
                    'address_longitude' => (float) 112.6139055,
                    'web_address' => 'https://um.ac.id',
                    'phone_number' => '0341-551611',
                    'email' => 'info@um.ac.id',
                    'youtube' => 'https://www.youtube.com/c/UniversitasNegeriMalang',
                    'instagram' => 'https://www.instagram.com/universitasnegerimalang',
                    'number_of_graduates' => 12000,
                    'number_of_registrants' => 25000,
                    'min_single_tuition' => 700000,
                    'max_single_tuition' => 20000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => 3890, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Negeri Surabaya',
                    'description' => 'Kec. Sukolilo, Kota Surabaya',
                    'date_of_establishment' => '1964-11-19',
                    'logo_path' => '/logo/logo_unesa.png',
                    'address_latitude' => (float) -7.3377771,
                    'address_longitude' => (float) 112.6883969,
                    'web_address' => 'https://unesa.ac.id',
                    'phone_number' => '031-8595222',
                    'email' => 'info@unesa.ac.id',
                    'youtube' => 'https://www.youtube.com/c/UNESAOfficial',
                    'instagram' => 'https://www.instagram.com/unesaofficial',
                    'number_of_graduates' => 8000,
                    'number_of_registrants' => 15000,
                    'min_single_tuition' => 1000000,
                    'max_single_tuition' => 15000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => 3906, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Negeri Medan',
                    'description' => 'Kec. BUNGUS TELUK KABUNG, Sumatera Barat',
                    'date_of_establishment' => '1999-08-04',
                    'logo_path' => '/logo/logo_unimed.png',
                    'address_latitude' => (float) -1.031713,
                    'address_longitude' => (float) 100.4284178,
                    'web_address' => 'https://unimed.ac.id',
                    'phone_number' => '061-7360521',
                    'email' => 'info@unimed.ac.id',
                    'youtube' => 'https://www.youtube.com/c/UniversitasNegeriMedan',
                    'instagram' => 'https://www.instagram.com/unimed_official',
                    'number_of_graduates' => 5000,
                    'number_of_registrants' => 10000,
                    'min_single_tuition' => 900000,
                    'max_single_tuition' => 20000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => 892, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Negeri Makassar',
                    'description' => 'Kec. Rappocini, Kota Makassar',
                    'date_of_establishment' => '1961-08-01',
                    'logo_path' => '/logo/logo_unm.png',
                    'address_latitude' => (float) -5.1733297,
                    'address_longitude' => (float) 119.4469508,
                    'web_address' => 'https://unm.ac.id',
                    'phone_number' => '0411-586992',
                    'email' => 'info@unm.ac.id',
                    'youtube' => 'https://www.youtube.com/c/UniversitasNegeriMakassar',
                    'instagram' => 'https://www.instagram.com/unmofficial',
                    'number_of_graduates' => 7000,
                    'number_of_registrants' => 14000,
                    'min_single_tuition' => 1000000,
                    'max_single_tuition' => 18000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => 5838, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Ahmad Dahlan Yogyakarta',
                    'description' => 'Kec. Kasihan, Kabupaten Bantul, Yogyakarta',
                    'date_of_establishment' => '1993-11-08',
                    'logo_path' => '/logo/logo_uad.png',
                    'address_latitude' => (float) -7.826463,
                    'address_longitude' => (float) 110.365054,
                    'web_address' => 'https://uad.ac.id',
                    'phone_number' => '0274-563019',
                    'email' => 'info@uad.ac.id',
                    'youtube' => 'https://www.youtube.com/c/UniversitasAhmadDahlan',
                    'instagram' => 'https://www.instagram.com/uad.yogyakarta',
                    'number_of_graduates' => 4000,
                    'number_of_registrants' => 10000,
                    'min_single_tuition' => 5000000,
                    'max_single_tuition' => 20000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $swasta_id, 
                    'district_id' => 3223, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Jember University',
                    'description' => 'Kec. Kaliwates, Kabupaten Jember',
                    'date_of_establishment' => '1964-04-01',
                    'logo_path' => '/logo/logo_unej.png',
                    'address_latitude' => (float) -8.169010,
                    'address_longitude' => (float) 113.707634,
                    'web_address' => 'https://unej.ac.id',
                    'phone_number' => '0331-330105',
                    'email' => 'info@unej.ac.id',
                    'youtube' => 'https://www.youtube.com/c/UniversitasJember',
                    'instagram' => 'https://www.instagram.com/universitasjember',
                    'number_of_graduates' => 6000,
                    'number_of_registrants' => 12000,
                    'min_single_tuition' => 800000,
                    'max_single_tuition' => 18000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => 346, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Riau',
                    'description' => 'Kec. Simpang Baru, Kabupaten Kampar, Riau',
                    'date_of_establishment' => '1962-09-01',
                    'logo_path' => '/logo/logo_unri.png',
                    'address_latitude' => (float) 0.500973,
                    'address_longitude' => (float) 101.447464,
                    'web_address' => 'https://unri.ac.id',
                    'phone_number' => '0761-63200',
                    'email' => 'info@unri.ac.id',
                    'youtube' => 'https://www.youtube.com/c/humasuniversitasriau',
                    'instagram' => 'https://www.instagram.com/universitas.riau/',
                    'number_of_graduates' => 7000,
                    'number_of_registrants' => 14000,
                    'min_single_tuition' => 900000,
                    'max_single_tuition' => 20000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => 1390, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'name' => 'Universitas Islam Negeri Sunan Gunung Djati',
                    'description' => 'Kec. Cibiru, Kota Bandung',
                    'date_of_establishment' => '1968-04-08',
                    'logo_path' => '/logo/logo_uin_sgd.png',
                    'address_latitude' => (float) -6.9163257,
                    'address_longitude' => (float) 107.7192104,
                    'web_address' => 'https://uinsgd.ac.id',
                    'phone_number' => '022-7803602',
                    'email' => 'info@uinsgd.ac.id',
                    'youtube' => 'https://www.youtube.com/@uinsgd.official',
                    'instagram' => 'https://www.instagram.com/uinsgd.official/',
                    'number_of_graduates' => 8000,
                    'number_of_registrants' => 15000,
                    'min_single_tuition' => 5000000,
                    'max_single_tuition' => 15000000,
                    'accreditation_id' => $unggul_id, 
                    'campus_type_id' => $ptn_id, 
                    'district_id' => 2569, 
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                

                [
                    'name' => 'Politeknik Kementrian Kesehatan Semarang',
                    'description' => 'Kec. Banyumanik, Kota Semarang',
                    'date_of_establishment' => '1995-06-06',
                    'logo_path' => '/logo/logo_polkesmar.png',
                    'address_latitude' => (float) -7.054530372005238,
                    'address_longitude' => (float) 110.42843222351858,
                    'web_address' => 'https://poltekkes-smg.ac.id',
                    'phone_number' => '024-74664321',
                    'email' => 'poltekkes-smg@poltekkes-smg.ac.id',
                    'youtube' => 'https://www.youtube.com/channel/UCkQtVFtysquY69uWhQLjHV',
                    'instagram' => 'https://www.instagram.com/polkessemarang/',
                    'number_of_graduates' => 500,
                    'number_of_registrants' => 900,
                    'min_single_tuition'=> 5450000,
                    'max_single_tuition'=> 12850000,
                    'accreditation_id' => $baik_sekali_id,
                    'campus_type_id' => $politeknik_id,
                    'district_id' => 3182,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        } else {
            echo "Akreditasi dengan nama 'Baik Sekali' tidak ditemukan.\n";
        }
    }
}
