<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudyProgramSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $accreditation = DB::table('accreditations')->where('name', 'Baik Sekali')->first();

        $S1 = DB::table('degree_levels')->where('name', 'S1')->first();
        $S2 = DB::table('degree_levels')->where('name', 'S2')->first();
        $MST = DB::table('degree_levels')->where('name', 'S2')->first();
        $D3 = DB::table('degree_levels')->where('name', 'D3')->first();
        $D4 = DB::table('degree_levels')->where('name', 'D4')->first();

        // poltekkes
        DB::table('study_programs')->insert([
            [
                'name' => 'Keperawatan Semarang',
                'description' => '(Unggul)',
                'campus_id' => 5,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 3,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Keperawatan Semarang dan Profesi Ners',
                'description' => '(B)',
                'campus_id' => 5,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 3,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kebidanan Semarang',
                'description' => '(Unggul)',
                'campus_id' => 5,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 4,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kebidanan Semarang dan Profesi Bidan',
                'description' => '(B)',
                'campus_id' => 5,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 4,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gizi Semarang',
                'description' => '(Unggul)',
                'campus_id' => 5,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 5,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gizi dan Dietetika',
                'description' => '(Unggul)',
                'campus_id' => 5,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 5,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Profesi Dietisien',
                'description' => '(B)',
                'campus_id' => 5,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 5,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Radiologi Semarang',
                'description' => '(Unggul)',
                'campus_id' => 5,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 6,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Radiologi Pencitraan Semarang',
                'description' => '(Unggul)',
                'campus_id' => 5,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 6,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kesehatan Gigi',
                'description' => '(Unggul)',
                'campus_id' => 5,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 7,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Terapi Gigi',
                'description' => '(Unggul)',
                'campus_id' => 5,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 7,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknologi Laboratorium Medis',
                'description' => '(B)',
                'campus_id' => 5,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 8,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknologi Laboratorium Medis',
                'description' => '(Unggul)',
                'campus_id' => 5,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 8,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknologi Bank Darah',
                'description' => '(Unggul)',
                'campus_id' => 5,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 8,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rekam Medis dan Informasi Kesehatan',
                'description' => '(Unggul)',
                'campus_id' => 5,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 9,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('study_programs')->insert([
            [
                'name' => 'Teknik Mesin',
                'description' => '(D3)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 10,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Konversi Energi',
                'description' => '(D3)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 10,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Mesin Produksi dan Perawatan',
                'description' => '(D4)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 10,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Rekayasa Pembangkit Energi',
                'description' => '(D4)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 10,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Listrik',
                'description' => '(D3)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 11,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Informatika',
                'description' => '(D3)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 11,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Elektronika',
                'description' => '(D3)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 11,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Rekayasa Elektronika',
                'description' => '(D4)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 11,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Telekomunikasi',
                'description' => '(D4)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 11,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Telekomunikasi',
                'description' => '(D3)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 11,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Rekayasa Instalasi Listrik',
                'description' => '(D4)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 11,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknologi Rekayasa Komputer',
                'description' => '(D4)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 11,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Telekomunikasi',
                'description' => '(MST)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $MST->id,
                'faculty_id' => 11,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Akuntansi',
                'description' => '(D3)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 12,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Keuangan dan Perbankan',
                'description' => '(D3)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 12,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Analisis Keuangan',
                'description' => '(D4)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 12,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Perbankan Syariah',
                'description' => '(D4)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 12,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Akuntansi Manajerial',
                'description' => '(D4)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 12,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Komputerisasi Akuntansi',
                'description' => '(D4)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 12,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Administrasi Bisnis',
                'description' => '(D3)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 13,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manajemen Pemasaran',
                'description' => '(D3)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 13,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manajemen Bisnis Internasional',
                'description' => '(D4)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 13,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Administrasi Bisnis Terapan',
                'description' => '(D4)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 13,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Konstruksi Gedung',
                'description' => '(D3)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 14,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Konstruksi Sipil',
                'description' => '(D3)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D3->id,
                'faculty_id' => 14,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Perbaikan dan Perawatan Gedung',
                'description' => '(D4)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 14,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Perancangan Jalan dan Jembatan',
                'description' => '(D4)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 14,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teknik Perbaikan dan Perawatan Gedung',
                'description' => '(D4 Lanjutan)',
                'campus_id' => 1,
                'accreditation_id' => $accreditation->id,
                'degree_level_id' => $D4->id,
                'faculty_id' => 14,
                'master_study_program_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);


    }
}
